[project]
name = 'Tokenized-Personal-Security-Consciousness-Privacy-Protection'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.privacy-protocol]
path = 'contracts/privacy-protocol.clar'
clarity_version = 2
epoch = 2.5

[contracts.provider-verification]
path = 'contracts/provider-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
